version: "3.8"
services:
  frontend:
    build: ./client
    container_name: frontend_client
    ports:
      - '3000:3000'
  backend:
    build: ./server
    container_name: backend_server
    ports:
      - '4000:4000'
    stdin_open: true
    tty: true